### ISSUE TITLE
Homework 03, Issue on Grader for Question 1.3

### ISSUE THREAD

**Issue by DDubeinSF** [ccsf-math-108/materials-fa21#4]
https://ccsf.cloudbank.2i2c.cloud/user/ddube1@mail.ccsf.edu/notebooks/materials-fa21/hw/hw03/student/hw03.ipynb

The grader for grader/comparison for question 1.3 is visible and gives a True output rather than the standard Pass output.

**Comment by shawnwiggins** [comment]
Resolved. Thanks!
