### ISSUE TITLE
Homework 03, Question 4 code already present.

### ISSUE THREAD

**Issue by DDubeinSF** [ccsf-math-108/materials-fa21#6]
https://ccsf.cloudbank.2i2c.cloud/user/ddube1@mail.ccsf.edu/notebooks/materials-fa21/hw/hw03/student/hw03.ipynb

It looks like you forgot to clear the code from when you took the class, oops.

**Comment by shawnwiggins** [comment]
The following code should be there. Is that what you are referring to?

boston = Table.read_table("boston.csv")
manila = Table.read_table("manila.csv")
print("Boston Table")
boston.show(4)
print("Manila Table")
manila.show(4)

**Comment by DDubeinSF** [comment]
Sorry, my bad. It's question 2.4 This whole line was already there:

less_than_west_births = pop.where('2016', are.below(west_births)).num_rows

**Comment by shawnwiggins** [comment]
resolved. Thanks again for all your feedback.
